"""empty message

Revision ID: 273efae933ae
Revises: 987b2de655d6
Create Date: 2026-03-26 13:09:23.845253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '273efae933ae'
down_revision = '987b2de655d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
