"""empty message

Revision ID: 847d56454d07
Revises: e8d6a8822866
Create Date: 2026-03-26 09:42:46.440529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847d56454d07'
down_revision = 'e8d6a8822866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('review')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
