"""empty message

Revision ID: 987b2de655d6
Revises: 847d56454d07
Create Date: 2026-03-26 10:20:49.936881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987b2de655d6'
down_revision = '847d56454d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
