"""empty message

Revision ID: cc07487e957f
Revises: 
Create Date: 2026-03-26 15:37:10.447932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc07487e957f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.Integer(), nullable=False))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('service_type')

    # ### end Alembic commands ###
